create table leads (
    id bigint generated by default as identity primary key,
    request_id uuid not null,
    payload_fingerprint bytea,
    name varchar(100),
    phone varchar(15),
    comment varchar(1000),
    source_path varchar(2048) not null,
    intent varchar(16) not null,
    consented_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    anonymized_at timestamp with time zone,
    constraint uk_leads_request_id unique (request_id),
    constraint ck_leads_intent check (intent in ('repair', 'maintenance')),
    constraint ck_leads_fingerprint check (
        payload_fingerprint is null or octet_length(payload_fingerprint) = 32
    ),
    constraint ck_leads_phone check (
        phone is null or length(phone) between 7 and 15
    ),
    constraint ck_leads_privacy check (
        (
            anonymized_at is null
            and payload_fingerprint is not null
            and name is not null
            and phone is not null
        )
        or
        (
            anonymized_at is not null
            and payload_fingerprint is null
            and name is null
            and phone is null
            and comment is null
        )
    )
);

create table telegram_outbox (
    id bigint generated by default as identity primary key,
    lead_id bigint not null,
    state varchar(16) not null,
    attempt_count integer not null default 0,
    next_attempt_at timestamp with time zone not null,
    lease_token uuid,
    lease_until timestamp with time zone,
    last_error_code varchar(64),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    delivered_at timestamp with time zone,
    constraint uk_telegram_outbox_lead_id unique (lead_id),
    constraint fk_telegram_outbox_lead
        foreign key (lead_id) references leads(id) on delete cascade,
    constraint ck_telegram_outbox_state check (
        state in ('pending', 'processing', 'retry', 'blocked', 'delivered')
    ),
    constraint ck_telegram_outbox_attempt_count check (attempt_count >= 0),
    constraint ck_telegram_outbox_shape check (
        (
            state = 'processing'
            and lease_token is not null
            and lease_until is not null
            and delivered_at is null
        )
        or
        (
            state in ('pending', 'retry', 'blocked')
            and lease_token is null
            and lease_until is null
            and delivered_at is null
        )
        or
        (
            state = 'delivered'
            and lease_token is null
            and lease_until is null
            and delivered_at is not null
        )
    )
);

create index idx_leads_retention
    on leads(created_at, id)
    where anonymized_at is null;

create index idx_leads_anonymized_cleanup
    on leads(anonymized_at, id)
    where anonymized_at is not null;

create index idx_telegram_outbox_claim
    on telegram_outbox(next_attempt_at, id)
    where state in ('pending', 'retry');

create index idx_telegram_outbox_expired_lease
    on telegram_outbox(lease_until, id)
    where state = 'processing';
